### ISSUE TITLE
Linear() extrapolation not supported (in outdated version)

### ISSUE THREAD

**Issue by lhapp27** [jipolanco/BSplineKit.jl#101]
Hi, thanks for the nice package.

I need to extrapolate my interpolated function, however I ran into an issue when trying to use the `Linear()` option. I used it as described in the documentation, but the error (see below) seems to suggst that the Linear option is not available yet? `Flat()`and `Smooth()` seem to work fine though. For my use-case the `Smooth()` option will probably do (need to test), but I think for the sake of completeness I want to report this issue.

```
julia> versioninfo()
Julia Version 1.10.4
...

julia> using BSplineKit

julia> xs = 0.2:0.2:1.2
0.2:0.2:1.2

julia> ys = 2 * cospi.(xs)
6-element Vector{Float64}:
  1.6180339887498947
  0.6180339887498947
 -0.6180339887498947
 -1.6180339887498951
 -2.0
 -1.6180339887498951

julia> S = interpolate(xs, ys, BSplineOrder(4))
SplineInterpolation containing the 6-element Spline{Float64}:
 basis: 6-element BSplineBasis of order 4, domain [0.2, 1.2]
 order: 4
 knots: [0.2, 0.2, 0.2, 0.2, 0.6, 0.8, 1.2, 1.2, 1.2, 1.2]
 coefficients: [1.61803, 1.13682, -0.301508, -2.08779, -2.14709, -1.61803]
 interpolation points: 0.2:0.2:1.2


julia> E_flat   = extrapolate(S, Flat())
SplineExtrapolation containing the 6-element Spline{Float64}:
 basis: 6-element BSplineBasis of order 4, domain [0.2, 1.2]
 order: 4
 knots: [0.2, 0.2, 0.2, 0.2, 0.6, 0.8, 1.2, 1.2, 1.2, 1.2]
 coefficients: [1.61803, 1.13682, -0.301508, -2.08779, -2.14709, -1.61803]
 extrapolation method: Flat()

julia> E_linear = extrapolate(S, Linear())
ERROR: UndefVarError: `Linear` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1

julia> E_smooth = extrapolate(S, Smooth())
SplineExtrapolation containing the 6-element Spline{Float64}:
 basis: 6-element BSplineBasis of order 4, domain [0.2, 1.2]
 order: 4
 knots: [0.2, 0.2, 0.2, 0.2, 0.6, 0.8, 1.2, 1.2, 1.2, 1.2]
 coefficients: [1.61803, 1.13682, -0.301508, -2.08779, -2.14709, -1.61803]
 extrapolation method: Smooth()
```

**Comment by jipolanco** [comment]
Hi, thanks for reporting this.

However your example works without error for me. Perhaps you are also loading a different package which also exports `Linear`? What happens if you try using `BSplineKit.Linear()` instead?

**Comment by lhapp27** [comment]
> Hi, thanks for reporting this.
> 
> However your example works without error for me. Perhaps you are also loading a different package which also exports `Linear`? What happens if you try using `BSplineKit.Linear()` instead?

Thanks for the quick reply.
Sorry my original message was not clear enough, but I used a fresh instance of julia without any other packages loaded, so there should not be any influence. Also I tried with `BSPlineKit.Linear()`, but the same error persists:

```
julia> E_linear = extrapolate(S, BSplineKit.Linear())
ERROR: UndefVarError: `Linear` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ REPL[9]:1

julia> BSplineKit.Linear()
ERROR: UndefVarError: `Linear` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ REPL[10]:1
```

It's a bit odd, maybe someone else can test it too?

**Comment by jipolanco** [comment]
Then you probably have an old version of BSplineKit.jl. The `Linear` extrapolation method was added in [v0.17.4](https://github.com/jipolanco/BSplineKit.jl/releases/tag/v0.17.4) (released on 08/07/2024).

What's the output of `using Pkg; Pkg.status("BSplineKit")`?
