### ISSUE TITLE
REPL crash with collocation on out-of-bounds points

### ISSUE THREAD

**Issue by asparc** [jipolanco/BSplineKit.jl#56]
Hi,

Unfortunately, I'm experiencing another issue with the library, particularly with the collocation_matrix function. I'm posting here two different cases that make my Julia REPL crash entirely:
 ```julia
B = BSplineBasis(4, [0.,1.])
pts = [-0.0,0.1]
collocation_matrix(B, pts, Derivative(0), Matrix{Float64})
```
and
```julia
B = BSplineBasis(4, [0.,1.])
pts = [-0.3,-0.2]
collocation_matrix(B, pts, Derivative(1), Matrix{Float64})
```
My first impression is that the issue has to do with the (negative) out of bounds evaluation points.

**Comment by jipolanco** [comment]
Thanks, this was caused by trying to assemble the collocation matrix while using `@inbounds`. Should be fixed by #57.
