### ISSUE TITLE
Global Bspline bases evaluations

### ISSUE THREAD

**Issue by rayqu1126** [jipolanco/BSplineKit.jl#83]
Hi,

@jlchan and I wonder if there is an easy way to construct a generalized Vandermonde whose columns correspond to evaluations of global Bspline bases at given points.

Right now we build 
`BsplineVandermonde(N, K, x) = hcat(PeriodicBSplineBasis(BSplineOrder(N+1), range(-1, 1, length=K+1))(x)[2]...)
BsplineVandermonde(N, K, x::AbstractVector) = vcat([BsplineVandermonde(N, K, xi) for xi in x]...)
`
but this only returns the evaluations of local Bspline bases, as you can see from this plot
`x = LinRange(-1,1,500);
V = BsplineVandermonde(4, 8, x);
scatter(x, V[:, 1], leg=false)`.

Thank you for providing this useful package and your help!

**Comment by jlchan** [comment]
Hi! Agreed with @rayqu1126 - thank you for providing this package! It's very nice to have the capability to work with periodic B-splines bases.

To clarify, we were wondering if there was existing functionality to compute a matrix whose entries are 

$V_{ij} = B_j(x_i)$

where $B_j(x)$ is a single Bspline basis function. From what we could see from the docs, `evaluate_all` and `PeriodicBSplineBasis` return the evaluation only of B-spline bases which are supported near the evaluation point.

**Comment by jlchan** [comment]
Update: I think we have it now. `evaluate` is what we were looking for.

For reference, this is 
```julia
function BsplineVandermonde(N, K, x) 
    bspline_basis = PeriodicBSplineBasis(BSplineOrder(N+1), range(-1, 1, length=K+1))
    return hcat([evaluate(bspline_basis, i, x) for i in 0:(N+K-1)]...)
end
```
which allows us to generate the following plot via
```julia
x = LinRange(-1,1,500)
V = BsplineVandermonde(3, 10, x)
scatter(x, V, legend=false)
```
<img width="697" alt="Screenshot 2024-01-11 at 11 42 21 PM" src="https://github.com/jipolanco/BSplineKit.jl/assets/1156048/35dcc366-50c2-46a8-809a-3b10ffea1dd0">

**Comment by jlchan** [comment]
@rayqu1126 I think we can close this now
